site_name: Issue 17
plugins:
  - awesome-pages
  # # Note: Uncomment the following lines to exhibit the buggy behaviour.
  # - mktheapidocs:
  #     modules:
  #       dummy_python_module:
  #         section: ""
  #         source_repo: "https://github.com/maxalbert/bug_reports/tree/master/mkdocs-awesome-pages-plugin/issue_17/dummy_python_module"
